plugins { id 'com.android.application' }

android {
    namespace 'com.example.hotspotproxy'
    compileSdk 36

    defaultConfig {
        applicationId 'com.example.hotspotproxy'
        minSdk 26
        targetSdk 36
        versionCode 7
        versionName '1.6'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
